# Generated by Django 3.0.5 on 2020-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200429_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('exp', 'Expense'), ('inc', 'Income')], default='inc', max_length=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
